{"name": "Проверка на получение зааказа для неавторизованного пользователя", "status": "passed", "start": 1730575327748, "stop": 1730575328070, "uuid": "0d76acfa-5e2a-4871-9e1e-820b13f73ef6", "historyId": "440f976b940da00bbca5ef539db77cc9", "testCaseId": "440f976b940da00bbca5ef539db77cc9", "fullName": "tests.test_get_user_orders.TestGetOrders#test_get_orders_unauthorized_user_successfully", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "DESKTOP-4QJCJVN"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}